// CharacterPrefills.ts
// Quick-fill presets for demo, side, and template characters.
// Import these into AddNewCharacter.tsx and wire up the prefill button.

import type { CharacterProfile } from "../types";

export type PrefillPreset = {
  label: string;
  emoji: string;
  description: string;
  profile: CharacterProfile;
  extra: {
    titles: string;
    hair: string;
    fashion: string;
    equipment: string;
    powers: string;
    orientation: string;
    bodyModifications: string;
    model: string;
  };
};

const blankExtra = {
  titles: "",
  hair: "",
  fashion: "",
  equipment: "",
  powers: "",
  orientation: "Heterosexual",
  bodyModifications: "",
  model: "",
};

// ─── Preset: Generic Side Character ─────────────────────────────────────────
const sideCharacterProfile: CharacterProfile = {
  identity: {
    name: "Alex Mercer",
    nickname: "Al",
    gender: "Man",
    family: "Estranged from parents, one younger sibling.",
    education: "High school diploma",
    address: "Downtown apartment, mid-city",
    languages: ["English"],
    career: ["Bartender"],
    pets: [],
    plants: [],
    religion: "Agnostic",
    favouriteColor: "Blue",
    favouriteFood: "Pizza",
    favouriteObject: "Old lighter",
    luckyNumber: 7,
    fears: ["Failure", "Being forgotten"],
    supernatural: {
      fightStyle: "",
      class: "",
      strengths: [],
      weaknesses: [],
      primaryElement: "",
      secondaryElement: "",
      tertiaryElement: "",
    },
  },
  anatomy: {
    age: 28,
    sex: "Male",
    race: "Human",
    species: "Human",
    bodyType: "Average",
    bloodType: "O+",
    height: "178cm",
    weight: "75kg",
    eyesight: "20/20",
    colorBlind: "None",
    glasses: false,
    handed: "Right",
    voice_type: "Mid baritone",
    scars: [],
    burns: [],
    skinDamage: [],
    tattoos: ["Small compass on left wrist"],
    birthmarks: [],
    nose: "Straight, unremarkable",
    eyes: "Brown, slightly tired",
    posture: "Relaxed slouch",
    breast: "",
    legs: "Average",
    moles: [],
  },
  personality: {
    sayings: '"Could be worse."',
    hobbies: "Pool, old movies, cooking simple meals.",
    habits: ["Taps the bar counter when thinking", "Always late by 5 minutes"],
    personality:
      "Laid-back and sardonic. Loyal to the people he likes, invisible to everyone else. Hides depth behind indifference.",
    insecurities: ["Feels like he peaked early", "Worried people find him boring"],
  },
  bio: {
    dob: "1996-03-14",
    dod: "",
    birthplace: "Cleveland, Ohio",
    surgeries: [],
    cavities: ["Lower left molar"],
    sexualHistory: [],
    currentLovers: [],
    pastLovers: ["Sarah K. (college)"],
    relationshipStatus: "Single",
    problemRelationships: "Complicated dynamic with his father.",
    familyRelationships: "Distant from family; moved out at 18.",
    friends: [],
    rivals: [],
    admires: [],
    hates: [],
    philosphyLove: "Love finds you when you stop chasing it.",
    phiolosphyRelationships:
      "Keep it simple. Don't owe anyone anything you can't give.",
    childhood: "Quiet suburban childhood. Nothing dramatic. That's the point.",
    criminalRecord: [],
    fears: [],
    successes: ["Opened his own bar tab at 24"],
    failures: ["Dropped out of community college"],
    dreams: ["Own a bar someday", "Travel to Japan"],
  },
  other: {
    inspiration: "Typical guy next door archetype",
    referenceImage: null,
  },
};

// ─── Preset: Demo Hero ───────────────────────────────────────────────────────
const demoHeroProfile: CharacterProfile = {
  identity: {
    name: "Zara Voss",
    nickname: "The Voss",
    gender: "Woman",
    family: "Daughter of a disgraced general. No siblings.",
    education: "Military academy, advanced combat training",
    address: "Nomadic — safehouse network",
    languages: ["English", "Mandarin", "Arabic"],
    career: ["Special Forces operative", "Freelance contractor"],
    pets: [],
    plants: [],
    religion: "Secular",
    favouriteColor: "Crimson",
    favouriteFood: "Black coffee and anything spicy",
    favouriteObject: "Titanium dog tag",
    luckyNumber: 13,
    fears: ["Losing her team", "Becoming her father"],
    supernatural: {
      fightStyle: "Close-quarters combat, dual pistols, tactical knives",
      class: "Rogue",
      strengths: ["Speed", "Improvisation", "Intimidation"],
      weaknesses: ["Trusts too few", "Reckless under emotional stress"],
      primaryElement: "",
      secondaryElement: "",
      tertiaryElement: "",
    },
  },
  anatomy: {
    age: 32,
    sex: "Female",
    race: "Mixed (German / Nigerian)",
    species: "Human",
    bodyType: "Athletic / muscular",
    bloodType: "A-",
    height: "172cm",
    weight: "68kg",
    eyesight: "Corrected to 20/15 (laser surgery)",
    colorBlind: "None",
    glasses: false,
    handed: "Ambidextrous",
    voice_type: "Low, clipped, commanding",
    scars: ["Knife scar left jaw", "Two gunshot scars right shoulder"],
    burns: [],
    skinDamage: [],
    tattoos: ["Unit insignia back of neck"],
    birthmarks: [],
    nose: "Strong, slightly crooked from a break",
    eyes: "Amber, sharp",
    posture: "Military-straight",
    breast: "Flat-chested, bound for combat",
    legs: "Powerful, runner's build",
    moles: ["Small one above left lip"],
  },
  personality: {
    sayings: '"Improvise, adapt, survive." | "Sentiment gets you killed."',
    hobbies: "Tactical puzzles, long-distance running, black-and-white photography.",
    habits: ["Scans exits in every room", "Cleans weapons at midnight"],
    personality:
      "Cold efficiency on the surface. Underneath: fierce protectiveness and guilt she refuses to name. Not cruel, but unsparing.",
    insecurities: [
      "That she is just like her father",
      "That she pushes everyone away before they can leave",
    ],
  },
  bio: {
    dob: "1992-11-02",
    dod: "",
    birthplace: "Berlin, Germany",
    surgeries: ["Shoulder reconstruction (x2)", "Laser eye correction"],
    cavities: [],
    sexualHistory: [],
    currentLovers: [],
    pastLovers: ["Marcus T. (KIA)", "Unnamed contact, classified"],
    relationshipStatus: "Single",
    problemRelationships: "Her father — General Voss — imprisoned for war crimes she helped expose.",
    familyRelationships: "No living close family.",
    friends: [],
    rivals: ["Ghost-7 (former colleague turned enemy)"],
    admires: [],
    hates: [],
    philosphyLove: "Love is a liability in her line of work. She knows this. She hates knowing it.",
    phiolosphyRelationships: "Transactional on the surface, deeply loyal once you earn it.",
    childhood:
      "Grew up on military bases. Taught discipline over affection. Learned to read people early — it was survival.",
    criminalRecord: ["Classified / sealed"],
    fears: [],
    successes: ["Dismantled three international weapons rings", "Testified against her own father"],
    failures: ["Lost her entire squad in the Karachi op"],
    dreams: ["Retire somewhere without a tactical perimeter", "Find out who Marcus really was"],
  },
  other: {
    inspiration: "Mara Jade, Black Widow, The Bride (Kill Bill)",
    referenceImage: null,
  },
};

const demoHeroExtra = {
  titles: "Commander (former)",
  hair: "Cropped undercut, natural black with faded silver streaks at temples.",
  fashion: "Tactical minimalist — matte black everything, form-fitting but functional. No jewelry except the dog tag.",
  equipment:
    "Twin Glock 19s (custom grips), ceramic combat knife, signal jammer wristband, collapsible baton.",
  powers: "Peak-human conditioning, tactical genius, close-quarters specialist.",
  orientation: "Bisexual",
  bodyModifications: "Knife scar left jaw, two gunshot entry/exit scars right shoulder, unit tattoo on neck.",
  model: "",
};

// ─── Preset: Villain / Antagonist ───────────────────────────────────────────
const villainProfile: CharacterProfile = {
  identity: {
    name: "Dorian Ashveil",
    nickname: "The Architect",
    gender: "Man",
    family: "Old money. Long line of manipulators. He considers himself the culmination.",
    education: "Oxford. Graduate of philosophy and economics.",
    address: "Private estate, undisclosed coastal location",
    languages: ["English", "French", "Latin"],
    career: ["CEO (front company)", "Shadow network operator"],
    pets: ["Albino python named Pale"],
    plants: ["Curated rare orchids"],
    religion: "Believes in power as the only honest religion.",
    favouriteColor: "Ivory",
    favouriteFood: "Rare steak, single-malt whisky",
    favouriteObject: "His late mother's chess set",
    luckyNumber: 0,
    fears: ["Insignificance", "Being genuinely known"],
    supernatural: {
      fightStyle: "Manipulation, proxy warfare, financial ruin",
      class: "Warlock",
      strengths: ["Foresight", "Patience", "Charisma"],
      weaknesses: ["Underestimates emotion in others", "Paranoid about betrayal"],
      primaryElement: "",
      secondaryElement: "",
      tertiaryElement: "",
    },
  },
  anatomy: {
    age: 51,
    sex: "Male",
    race: "White (British)",
    species: "Human",
    bodyType: "Lean, elegant",
    bloodType: "AB+",
    height: "188cm",
    weight: "82kg",
    eyesight: "Perfect — unnervingly so",
    colorBlind: "None",
    glasses: false,
    handed: "Left",
    voice_type: "Cultured baritone, measured cadence",
    scars: [],
    burns: [],
    skinDamage: [],
    tattoos: [],
    birthmarks: [],
    nose: "Aquiline, aristocratic",
    eyes: "Pale grey, unsettling steadiness",
    posture: "Impeccable",
    breast: "",
    legs: "Long, unhurried gait",
    moles: [],
  },
  personality: {
    sayings:
      '"People don\'t want freedom. They want permission." | "I don\'t win arguments. I render them irrelevant."',
    hobbies: "Chess, art acquisition, long-term planning.",
    habits: ["Never raises his voice", "Always arrives first, leaves last", "Reads people as entertainment"],
    personality:
      "Glacially calm, surgically intelligent. Genuinely believes he is serving humanity by controlling it. Makes evil look like vision.",
    insecurities: [
      "His mother never believed he was enough",
      "Terrified no one will understand his plan until it's too late — and then no one will care",
    ],
  },
  bio: {
    dob: "1973-01-17",
    dod: "",
    birthplace: "Edinburgh, Scotland",
    surgeries: [],
    cavities: [],
    sexualHistory: [],
    currentLovers: [],
    pastLovers: [],
    relationshipStatus: "Single",
    problemRelationships: "Destroyed two former partners financially. Considers it a kindness.",
    familyRelationships:
      "Mother died when he was 19. Left everything to charity, not him. He's been proving something ever since.",
    friends: [],
    rivals: ["Zara Voss"],
    admires: [],
    hates: [],
    philosphyLove:
      "Love is a leverage point. Nothing more, nothing less. He's too honest to pretend otherwise.",
    phiolosphyRelationships:
      "Every relationship is a transaction. He simply does not lie about this.",
    childhood:
      "Cold, gilded, and loveless. Attended every elite institution. Excelled at everything. Felt nothing.",
    criminalRecord: ["Nothing provable"],
    fears: [],
    successes: ["Controls four governments indirectly", "Has never been indicted"],
    failures: ["Let emotion cloud one decision in 2009. One person escaped. He has not repeated the error."],
    dreams: ["A world that runs exactly as he designed. Nothing else."],
  },
  other: {
    inspiration: "Hannibal Lecter, Ra's al Ghul, Logan Roy",
    referenceImage: null,
  },
};

const villainExtra = {
  titles: "Dr., Lord (disputed title)",
  hair: "Silver-white, swept back, immaculate.",
  fashion:
    "Bespoke everything. Dark charcoal suits, no tie. Simple, expensive, and always slightly too formal for any situation.",
  equipment:
    "Encrypted satellite phone, private security detail (offsite), shell company network.",
  powers: "Influence, wealth, network of proxies. No direct combat ability — by choice.",
  orientation: "Asexual",
  bodyModifications: "None. The body is merely the vehicle.",
  model: "",
};

// ─── Preset: Fantasy Mage ────────────────────────────────────────────────────
const fantasyMageProfile: CharacterProfile = {
  identity: {
    name: "Sylvara Moonwhisper",
    nickname: "Syl",
    gender: "Woman",
    family: "Born to a long line of court mages. Last surviving member.",
    education: "Arcane Academy, 12 years. Self-taught in forbidden texts.",
    address: "Tower at the edge of the Ashwood",
    languages: ["Common", "Elvish", "Draconic", "Sylvan"],
    career: ["Court Mage (former)", "Independent Scholar"],
    pets: ["Familiar: silver owl named Inx"],
    plants: ["Moonflower garden", "Poisonroot collection (research)"],
    religion: "Worships Selûne, goddess of the moon",
    favouriteColor: "Silver",
    favouriteFood: "Honeyed tea, stardust cakes",
    favouriteObject: "Cracked spellbook from her mentor",
    luckyNumber: 3,
    fears: ["Losing her magic", "Being the last of her line"],
    supernatural: {
      fightStyle: "Ranged spellcasting, illusion and moon magic",
      class: "Wizard",
      strengths: ["Arcane knowledge", "Illusion magic", "Strategic patience"],
      weaknesses: ["Fragile physically", "Overthinks in crisis"],
      primaryElement: "Moon / Light",
      secondaryElement: "Ice",
      tertiaryElement: "",
    },
  },
  anatomy: {
    age: 247,
    sex: "Female",
    race: "High Elf",
    species: "Elf",
    bodyType: "Willowy, slender",
    bloodType: "Unknown (elvish)",
    height: "168cm",
    weight: "52kg",
    eyesight: "Darkvision, 60ft",
    colorBlind: "None",
    glasses: false,
    handed: "Right",
    voice_type: "Soft, precise, melodic",
    scars: ["Runic burn scar on right palm from a spell gone wrong"],
    burns: [],
    skinDamage: [],
    tattoos: ["Constellation map on her left shoulder blade (self-applied, magical ink)"],
    birthmarks: [],
    nose: "Delicate, slightly upturned",
    eyes: "Silver-violet, luminescent in darkness",
    posture: "Tall and unhurried, head always slightly tilted as if listening",
    breast: "",
    legs: "Long, graceful",
    moles: [],
  },
  personality: {
    sayings: '"The stars remember what mortals forget." | "Knowledge is not power. Wisdom is."',
    hobbies: "Stargazing, translating ancient texts, enchanting small objects for fun.",
    habits: ["Mutters spell components absentmindedly", "Never sits with her back to a door"],
    personality:
      "Quiet and observant. Gentle in most things, but with a spine of cold iron when it matters. Has lived long enough to find mortals both exhausting and endearing.",
    insecurities: [
      "That her magic comes too easily, and she has never truly suffered for it",
      "That she outlives everyone she loves",
    ],
  },
  bio: {
    dob: "Spring, Year of the Third Moon (247 years ago)",
    dod: "",
    birthplace: "Silvergate, the High Elvish Reaches",
    surgeries: [],
    cavities: [],
    sexualHistory: [],
    currentLovers: [],
    pastLovers: ["Erindal (died 80 years ago)", "A human mage whose name she no longer speaks aloud"],
    relationshipStatus: "Single",
    problemRelationships:
      "Her former patron — the king — blamed her for failing to prevent the court massacre. She blames herself too.",
    familyRelationships: "All dead. She is the last.",
    friends: [],
    rivals: [],
    admires: [],
    hates: [],
    philosphyLove:
      "She loves deeply and rarely. She has learned to love the leaving, because it is the only thing that comes reliably.",
    phiolosphyRelationships:
      "Brief by necessity, sincere by nature. She does not pretend connections are less than they are.",
    childhood:
      "Magical, structured, lonely. Gifted too early. Her teachers were impressed; her family was afraid.",
    criminalRecord: ["Destruction of a noble estate (justified, sealed by royal decree)"],
    fears: [],
    successes: ["Translated the Athenaeum of Shadows", "Sealed the Ashwood Rift"],
    failures: ["Did not see the court betrayal coming", "Lost three apprentices in ten years"],
    dreams: ["Find the answer to the Last Question (she won't say what it is)", "Rest, eventually"],
  },
  other: {
    inspiration: "Galadriel, Hermione Granger (older), Le Guin's Ged",
    referenceImage: null,
  },
};

const fantasyMageExtra = {
  titles: "Archmagus (former), Scholar",
  hair: "Long platinum-white, loose and flowing with small braids near the temples.",
  fashion: "Deep indigo robes with silver thread constellations. Minimalist jewelry: one silver ring on each hand.",
  equipment:
    "Moonstaff (focus), spellbook (cracked but intact), pouch of reagents, enchanted map.",
  powers:
    "Arcane spellcasting (Wizard, Divination subclass). Moonbeam, counterspell, time-stop (limited). Familiar bond.",
  orientation: "Pansexual",
  bodyModifications:
    "Runic burn scar on right palm. Constellation tattoo on left shoulder blade.",
  model: "",
};

// ─── Empty / Blank Slate ─────────────────────────────────────────────────────
const blankProfile: CharacterProfile = {
  identity: {
    name: "",
    nickname: "",
    gender: "",
    family: "",
    education: "",
    address: "",
    languages: [],
    career: [],
    pets: [],
    plants: [],
    religion: "",
    favouriteColor: "",
    favouriteFood: "",
    favouriteObject: "",
    luckyNumber: 0,
    fears: [],
    supernatural: {
      fightStyle: "",
      class: "",
      strengths: [],
      weaknesses: [],
      primaryElement: "",
      secondaryElement: "",
      tertiaryElement: "",
    },
  },
  anatomy: {
    age: 25,
    sex: "Male",
    race: "",
    species: "",
    bodyType: "",
    bloodType: "",
    height: "",
    weight: "",
    eyesight: "",
    colorBlind: "",
    glasses: false,
    handed: "",
    voice_type: "",
    scars: [],
    burns: [],
    skinDamage: [],
    tattoos: [],
    birthmarks: [],
    nose: "",
    eyes: "",
    posture: "",
    breast: "",
    legs: "",
    moles: [],
  },
  personality: {
    sayings: "",
    hobbies: "",
    habits: [],
    personality: "",
    insecurities: [],
  },
  bio: {
    dob: "",
    dod: "",
    birthplace: "",
    surgeries: [],
    cavities: [],
    sexualHistory: [],
    currentLovers: [],
    pastLovers: [],
    relationshipStatus: "",
    problemRelationships: "",
    familyRelationships: "",
    friends: [],
    rivals: [],
    admires: [],
    hates: [],
    philosphyLove: "",
    phiolosphyRelationships: "",
    childhood: "",
    criminalRecord: [],
    fears: [],
    successes: [],
    failures: [],
    dreams: [],
  },
  other: {
    inspiration: "",
    referenceImage: null,
  },
};

// ─── Export ──────────────────────────────────────────────────────────────────
export const PREFILL_PRESETS: PrefillPreset[] = [
  {
    label: "Side Character",
    emoji: "🎭",
    description: "A grounded, ordinary background character. Good for NPCs or supporting roles.",
    profile: sideCharacterProfile,
    extra: { ...blankExtra },
  },
  {
    label: "Demo Hero",
    emoji: "⚔️",
    description: "A battle-hardened female operative. Ready for action-heavy stories.",
    profile: demoHeroProfile,
    extra: demoHeroExtra,
  },
  {
    label: "Villain",
    emoji: "🕰️",
    description: "A cold, calculating antagonist. Power, manipulation, old money.",
    profile: villainProfile,
    extra: villainExtra,
  },
  {
    label: "Fantasy Mage",
    emoji: "🌙",
    description: "An ancient elvish wizard. Perfect for high-fantasy settings.",
    profile: fantasyMageProfile,
    extra: fantasyMageExtra,
  },
  {
    label: "Clear Form",
    emoji: "✕",
    description: "Reset everything and start fresh.",
    profile: blankProfile,
    extra: { ...blankExtra },
  },
];